name: hush
version: 0.1.0.0
synopsis: Haskell wrapper for Unsplash API. 
maintainer: Deniz Alp Durmaz <denizalpd@ogr.iu.edu.tr>
category: Web
license: BSD3
default-extensions:
  - OverloadedStrings
  - RecordWildCards
  - LambdaCase
extra-source-files:
  - CHANGELOG.md
  - README.md

ghc-options:
  -Wall

dependencies:
  - base

library:
  source-dirs:
    - src
  dependencies:
    - aeson
    - http-client
    - http-client-tls
    - lens
    - load-env
    - servant
    - servant-client
    - text
    - tls